### ISSUE TITLE
Gagal Membuat Campaign

### ISSUE THREAD

**Issue by BJS611** [BladeKnife/ytviews#1]
Semua data benar dan Coins gw banyak tapi gw gk tahu ini kenapa

{!}Loading...100%Traceback (most recent call last):     File "sub.py", line 169, in <module>
    tod=c["campaignId"]
KeyError: 'campaignId'

**Comment by KangTeknisi** [comment]
> Semua data benar dan Coins gw banyak tapi gw gk tahu ini kenapa
> 
> {!}Loading...100%Traceback (most recent call last): File "sub.py", line 169, in
> tod=c["campaignId"]
> KeyError: 'campaignId'

udah install bs4,mechanize,request? oh iya kalau pengen view bot lagi usahain hanya 1 kali kalau anda setting viewbot 1000 waktu tunggu akan lama, saran saya 10 view tiap 1 hari/50 view.

**Comment by BJS611** [comment]
> > Semua data benar dan Coins gw banyak tapi gw gk tahu ini kenapa
> > 
> > {!}Loading...100%Traceback (most recent call last): File "sub.py", line 169, in
> > tod=c["campaignId"]
> > KeyError: 'campaignId'
> 
> udah install bs4,mechanize,request? oh iya kalau pengen view bot lagi usahain hanya 1 kali kalau anda setting viewbot 1000 waktu tunggu akan lama, saran saya 10 view tiap 1 hari/50 view.

Waduh, saya malah maksakan 1000 Views, dengan koin yg sudah ada 10000  koin lebih 😂

**Comment by KangTeknisi** [comment]
> > > Semua data benar dan Coins gw banyak tapi gw gk tahu ini kenapa
> > > {!}Loading...100%Traceback (most recent call last): File "sub.py", line 169, in
> > > tod=c["campaignId"]
> > > KeyError: 'campaignId'
> > 
> > 
> > udah install bs4,mechanize,request? oh iya kalau pengen view bot lagi usahain hanya 1 kali kalau anda setting viewbot 1000 waktu tunggu akan lama, saran saya 10 view tiap 1 hari/50 view.
> 
> Waduh, saya malah maksakan 1000 Views, dengan koin yg sudah ada 10000 koin lebih 😂

ya next video minimal 10 atau 50 tapi coba aja 100 view per hari/minggu soalnya viewbot ini lama tapi aman.

**Comment by BJS611** [comment]
> > > > Semua data benar dan Coins gw banyak tapi gw gk tahu ini kenapa
> > > > {!}Loading...100%Traceback (most recent call last): File "sub.py", line 169, in
> > > > tod=c["campaignId"]
> > > > KeyError: 'campaignId'
> > > 
> > > 
> > > udah install bs4,mechanize,request? oh iya kalau pengen view bot lagi usahain hanya 1 kali kalau anda setting viewbot 1000 waktu tunggu akan lama, saran saya 10 view tiap 1 hari/50 view.
> > 
> > Waduh, saya malah maksakan 1000 Views, dengan koin yg sudah ada 10000 koin lebih 😂
> 
> ya next video minimal 10 atau 50 tapi coba aja 100 view per hari/minggu soalnya viewbot ini lama tapi aman.

Sip, terimakasih mas
